services:
  app:
    build:
      context: .
      target: base
      secrets:
        - GITHUB_TOKEN
        - COMPOSER_TOKEN
      args:
        APP_ENV: "development"
    container_name: multi-image-pod-app
    environment:
      APP_ENV: "${APP_ENV}"
      SERVICE_ROLE: "${SERVICE_ROLE:-web,cron}"
      OPCACHE_ENABLE: "${OPCACHE_ENABLE:-0}"
      XDEBUG_ENABLE: "${XDEBUG_ENABLE:-0}"
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_CLIENT_HOST: "${XDEBUG_CLIENT_HOST:-172.17.0.1}"
      XDEBUG_CLIENT_PORT: "${XDEBUG_CLIENT_PORT:-9003}"
      XDEBUG_CONFIG_EXTRA: "${XDEBUG_CONFIG_EXTRA:-xdebug.start_with_request=yes;}"
    networks:
      - multi-image-pod

  nginx:
    image: public.ecr.aws/nginx/nginx:latest
    container_name: multi-image-pod-nginx
    ports:
      - "8080:80"
      - "426:426"
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    networks:
      - multi-image-pod

networks:
  multi-image-pod:
    driver: bridge

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  COMPOSER_TOKEN:
    environment: COMPOSER_TOKEN
