global:
  secretStoreName: "app-external-aws.application"
  serviceAccountName: applicationServiceName
external-secret:
  enabled: false
web:
  enabled: true
  virtualService:
    enabled: false
  replicas: 1
  name: nginx
  image:
    repository: public.ecr.aws/nginx/nginx
    tag: latest
  ports:
    - name: http
      appPort: 80
      servicePort: 80
      protocol: TCP
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  autoscaling:
    enabled: false
    minReplicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  metric:
    enabled: false
  extraVolumeMounts:
    - name: nginx-config-alpha
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
      subPath: nginx
    - name: nginx-config-alpha
      mountPath: /etc/nginx/conf.d/default.conf
      readOnly: true
      subPath: virtualhost
  extraVolumes:
    - name: nginx-config-alpha
      configMap:
        name: nginx-config-alpha
  extraContainers:
    - name: php
      image: bobrovskyi4pdffiller/multicontainer-pod-example-php:1.0
      envFrom:
        - configMapRef:
            name: configmap-name
        - secretRef:
            name: secret-name
      env:
        - name: APP_ENV
          value: "production"
        - name: OPCACHE_ENABLE
          value: "0"
migration-job:
  enabled: false
  command: ["php"]
  args: ["bin/console", "doctrine:migrations:migrate", "--no-interaction"]
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
tr-sync-pending-refund:
  enabled: false