#!/bin/bash
db_name_test="${DB_NAME}_test"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DB_USER WITH SUPERUSER PASSWORD '$DB_PASSWORD';
    CREATE DATABASE $DB_NAME WITH ENCODING='UTF8' CONNECTION LIMIT=-1 OWNER=$DB_USER;
    CREATE DATABASE "$db_name_test" WITH ENCODING='UTF8' CONNECTION LIMIT=-1 OWNER=$DB_USER;
EOSQL