apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-{{ $.Values.global.deployment_variant }}
  labels:
    app: {{ $.Values.global.app_name }}
data:
  nginx: |
    user  nginx;
    worker_processes  auto;
    
    error_log  /proc/self/fd/2 notice;
    pid        /var/run/nginx.pid;
    
    events {
      worker_connections  1024;
    }
    
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
    
      log_format json_combined escape=json '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"remote_user":"$remote_user",'
        '"request":"$request",'
        '"status":$status,'
        '"body_bytes_sent":$body_bytes_sent,'
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
      '}';
    
      access_log /proc/self/fd/1 json_combined;      
      sendfile        on;
      keepalive_timeout  65;      
      include /etc/nginx/conf.d/*.conf;
    }
  virtualhost: |
    server {
      listen 80 default_server;
      server_name your-domain-name;
    
      index index.php;
      root /app/public;
    
      charset utf-8;
    
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }
    
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass             localhost:9000;
        fastcgi_index            index.php;
    
        include                  fastcgi_params;
    
        fastcgi_param            SCRIPT_FILENAME $document_root$fastcgi_script_name;
    
        fastcgi_pass_request_headers on;
        fastcgi_pass_header  Status;
    
        fastcgi_intercept_errors off;
        fastcgi_read_timeout     300;
        fastcgi_buffer_size      16k;
        fastcgi_buffers          4 16k;
      }
    }
    
    server {
      listen 426 default_server;
      server_name your-domain-name;
      return 426 "This service requires use of the HTTPS protocol";
    }